In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv("Iris.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [6]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [7]:
L=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
x=df[L]
y=df['Species']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [10]:
from sklearn.svm import SVC

In [11]:
s=SVC()

In [12]:
s.fit(x_train,y_train)

SVC()

In [13]:
pre=s.predict(x_test)

In [14]:
print(pre)

['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica']


In [15]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [16]:
print(classification_report(y_test,pre))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       1.00      1.00      1.00        11
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [17]:
print(accuracy_score(y_test,pre))

1.0


In [18]:
print(confusion_matrix(y_test,pre))

[[ 8  0  0]
 [ 0 11  0]
 [ 0  0 11]]


In [20]:
s.support_vectors_# to get list of instances to get support vector

array([[5.1, 3.8, 1.9, 0.4],
       [4.5, 2.3, 1.3, 0.3],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [6. , 3.4, 4.5, 1.6],
       [6.4, 3.2, 4.5, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [6.3, 3.3, 4.7, 1.6],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [6.7, 3.1, 4.7, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.2, 2.2, 4.5, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.4, 3. , 4.5, 1.5],
       [6.1, 3. , 4.6, 1.4],
       [5. , 2. , 3.5, 1. ],
       [6.9, 3.1, 4.9, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [5. , 2.3, 3.3, 1. ],
       [6. , 2.9, 4.5, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [5.5, 2.6, 4.4, 1.2],
       [5.7, 2.6, 3.5, 1. ],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.7, 5.1, 1.6],
       [6.6, 3. , 4.4, 1.4],
       [4.9, 2.5, 4.5, 1.7],
       [6.1, 2.6, 5.6, 1.4],
       [5.7, 2.5, 5. , 2. ],
       [6.4, 3.2, 5.3, 2.3],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2

In [21]:
s.n_support_# to find out how much instances are take form each classes

array([ 5, 24, 21])